### PR TITLE
Catch formatError

### LINKED ISSUE #171: Loading query for ever when there are syntax errors
I've noticed that each time I run a query with a error it stays loading for a lot of time and then it responds:

```
TypeError: Failed to fetch
    at TypeError (native)
```

In the server it logs 

```
(STDERR) GraphQL Error: Cannot query field "dme" on type "Query". Did you mean "me"?
(STDERR) GraphQL Error: Cannot read property '0' of undefined
```

I think we are missing a ```try/catch``` in the server.

I'm using Apollo with Meteor.

Is anyone else having this error?

### PR DESCRIPTION
**Pull request by nicolaslopezj**
When formatError throws an error, the request nevers responds. In this PR I add try/catch to formatError and use the default one if the provided fails.

This fixes #171 

TODO:

- [x] Update CHANGELOG.md with your change (include reference to issue & this PR)
- [x] Make sure all of the significant new logic is covered by tests
- [x] Rebase your changes on master so that they can be merged easily
- [x] Make sure all tests and linter rules pass

### CODE REVIEW

File: src/core/runQuery.ts [hunk 1]
```diff
@@ -69,11 +69,18 @@ function doRunQuery(options: QueryOptions): Promise<GraphQLResult> {
...
-        // GraphQLResult returns Array<GraphQLError>, but the formatError function
-        // returns Array<GraphQLFormattedError>
-        return errors.map(options.formatError || formatError as any) as Array<Error>;
+        return errors.map((error) => {
+          if (options.formatError) {
+            try {
+              return options.formatError(error);
+            } catch (err) {
+              console.error('Error in formatError function:', err);
+              return formatError(error);
```
Comment (stubailo) [inline src/core/runQuery.ts]: People might be using `formatError` to hide some information, for example maybe they don't want the error message to leak to the client. I'd suggest the best option is to return a generic "Internal server error" message instead.

Comment (nicolaslopezj) [inline src/core/runQuery.ts]: fixed

**Comment by stubailo** [comment]
Looks great to me, thanks!
